denoise_strategy: "HMPWMCSFScrubGS"
smooth_fwhm: 6
n_jobs: 1

preproc: /Volumes/MRI/mfc/derivatives/fmriprep/sub-mfc{sub}/func/sub-mfc{sub}_task-{task}_acq-epi_rec-fmap_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz
preproc_to_pfc: data/sub-{sub}/sub-{sub}_task-{task}_atlas-schaefer100_denoise-HMPWMCSFScrubGS_ppi.npy
agg_pfc: data/group/atlas-schaefer100_denoise-HMPWMCSFScrubGS_ppi.npy
